# Generated by Django 4.2.10 on 2026-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Xidmət adı')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('category', models.CharField(choices=[('main', 'Əsas xidmətlər'), ('additional', 'Əlavə xidmətlər')], default='main', max_length=32, verbose_name='Kateqoriya')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=80, verbose_name='Soyad')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Telefon nömrəsi')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron mail')),
                ('company_name', models.CharField(blank=True, max_length=120, verbose_name='Şirkət adı')),
                ('message', models.TextField(blank=True, verbose_name='Qeyd')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ümumi qiymət')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('contacted', 'Əlaqə saxlanılıb'), ('in_progress', 'İcradadır'), ('completed', 'Tamamlanıb'), ('cancelled', 'Ləğv edilib')], default='new', max_length=32, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('services', models.ManyToManyField(related_name='calculator_requests', to='calculator.service', verbose_name='Xidmətlər')),
            ],
            options={
                'verbose_name': 'Calculator müraciəti',
                'verbose_name_plural': 'Calculator müraciətləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
