# Generated by Django 4.2.10 on 2026-08-29 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('quoted', 'Qiymət hesablanıb'), ('closed', 'Bağlanıb')], default='active', max_length=16)),
                ('context_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Söhbət',
                'verbose_name_plural': 'Söhbətlər',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='AZN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_quotes', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Hesablanmış qiymət',
                'verbose_name_plural': 'Hesablanmış qiymətlər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('website', 'Sayt növü'), ('feature', 'Funksiya'), ('design', 'Dizayn'), ('infrastructure', 'Domain və hosting'), ('seo', 'SEO'), ('page', 'Əlavə səhifə'), ('other', 'Digər')], max_length=24)),
                ('website_type', models.CharField(blank=True, choices=[('corporate', 'Korporativ sayt'), ('clinic', 'Klinik saytı'), ('restaurant', 'Restoran saytı'), ('hotel', 'Otel saytı'), ('store', 'Mağaza saytı'), ('education', 'Təhsil saytı'), ('portfolio', 'Portfolio'), ('other', 'Digər')], max_length=24)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_mode', models.CharField(choices=[('flat', 'Sabit qiymət'), ('per_unit', 'Vahid üzrə')], default='flat', max_length=16)),
                ('included_units', models.PositiveIntegerField(default=0)),
                ('unit_label', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qiymət xidməti',
                'verbose_name_plural': 'Qiymət xidmətləri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(blank=True)),
                ('website_type', models.CharField(blank=True, choices=[('corporate', 'Korporativ sayt'), ('clinic', 'Klinik saytı'), ('restaurant', 'Restoran saytı'), ('hotel', 'Otel saytı'), ('store', 'Mağaza saytı'), ('education', 'Təhsil saytı'), ('portfolio', 'Portfolio'), ('other', 'Digər')], max_length=24)),
                ('business_sector', models.CharField(blank=True, max_length=160)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('design', models.CharField(blank=True, max_length=160)),
                ('domain_needed', models.BooleanField(blank=True, null=True)),
                ('hosting_needed', models.BooleanField(blank=True, null=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='chatbot.conversation')),
                ('selected_services', models.ManyToManyField(blank=True, related_name='requirements', to='chatbot.pricingservice')),
            ],
            options={
                'verbose_name': 'Sayt tələbi',
                'verbose_name_plural': 'Sayt tələbləri',
            },
        ),
        migrations.CreateModel(
            name='PriceQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='chatbot.pricequote')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='chatbot.pricingservice')),
            ],
            options={
                'verbose_name': 'Qiymət sətri',
                'verbose_name_plural': 'Qiymət sətirləri',
            },
        ),
        migrations.AddField(
            model_name='pricequote',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_quotes', to='chatbot.websiterequirement'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Müştəri'), ('bot', 'Bot')], max_length=8)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=48)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Müştəri məlumatı',
                'verbose_name_plural': 'Müştəri məlumatları',
            },
        ),
    ]
